### ISSUE TITLE
UMD-Build missing

### ISSUE THREAD

**Issue by ryoshi1986** [AllenWooooo/rc-datetime-picker#57]
Hi there,

the umd isn´t available, would you be so kind and fix this? I really want to introduce this nice datetime-picker to my colleagues.

/*
 * rc-datetime-picker v1.6.1
 * https://github.com/AllenWooooo/rc-datetime-picker
 *
 * (c) 2018 Allen Wu
 * License: MIT
 */
undefined

Thanks in advance!

Greetings
David

**Comment by smrsan76** [comment]
Hi @ryoshi1986 

I think, This package is no longer maintained...
And because of this, I've re-published it as "imrc-datetime-picker" package with so many improvements.

You could use "[imrc-datetime-picker](https://npmjs.com/package/imrc-datetime-picker)" package
and your contributions are appreciated.

Best wishes 👍

**Comment by ryoshi1986** [comment]
Thx for your comment. In the end we went with the [material-ui-pickers](https://github.com/dmtrKovalenko/material-ui-pickers)
